addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("com.scalapenos" % "sbt-prompt" % "1.0.2")
addSbtPlugin("de.heikoseeberger" % "sbt-groll" % "6.0.0")
//addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.4.0")
//addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.6.0")